In [0]:
import numpy as np

arr_list=[]
old = np.zeros((5,5))

old[0][1]=1
old[1][2]=1
old[2][1]=1
old[2][2]=1
old[2][4]=1
old[3][1]=1
old[3][4]=1

arr_list.append(old)

print("Time - 0")
print(old)
print("\n\n")
for k in range(0,3):
    new = np.zeros((5,5))
    for i in range(0,5):
        for j in range(0,5):
            neighbours = 0
            
            if i==0 and j==0:
                neighbours= old[i][j+1] + old[i+1][j] + old[i+1][j+1] 
            if i==0 and j==4:
                neighbours= old[i][j-1] + old[i+1][j] + old[i+1][j-1]

            if i==4 and j==0:
                neighbours= old[i][j+1] + old[i-1][j] + old[i-1][j+1]
            if i==4 and j==4:
                neighbours= old[i][j-1] + old[i-1][j] + old[i-1][j-1]
            
            if i==0 and j>0 and j<4:
                neighbours= old[i][j-1] + old[i][j+1] + old[i+1][j-1] + old[i+1][j] + old[i+1][j+1]
            if i==4 and j>0 and j<4:
                neighbours= old[i][j-1] + old[i][j+1] + old[i-1][j-1] + old[i-1][j] + old[i-1][j+1]
            
            if j==0 and i>0 and i<4:
                neighbours= old[i-1][j] + old[i+1][j] + old[i-1][j+1] + old[i][j+1] + old[i+1][j+1]
            if j==4 and i>0 and i<4:
                neighbours= old[i-1][j] + old[i+1][j] + old[i-1][j-1] + old[i][j-1] + old[i+1][j-1]
            
            if  i>0 and i<4 and j>0 and j<4:
                neighbours= old[i-1][j-1] + old[i-1][j] + old[i-1][j+1] + old[i][j-1] + old[i][j+1] + old[i+1][j-1] + old[i+1][j] + old[i+1][j+1] 

            #if old[i][j] == 1:
            #    print (str(i) + " " + str(j) + " " +str(neighbours))
            
            if old[i][j] == 1 and neighbours <2 :
                new[i][j] = 0
            if old[i][j] == 1 and neighbours >3 :
                new[i][j] = 0
            if old[i][j] == 1 and neighbours >1 and neighbours <4 :
                new[i][j] = 1
            if old[i][j] == 0 and neighbours == 3 :
                new[i][j] = 1
    print("Time - " + str(k+1))
    print(new)
    print()
    arr_list.append(new)
    old=new



Time - 0
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 1. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]



Time - 1
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0.]
 [0. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

Time - 2
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]

Time - 3
[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]]

